import React, { useState } from "react";
import { User, UserRole, AppState } from "../types";
import { fetchStoreFromFirestore, saveStore, getStore, saveUser } from "../store";
import {
  Mail,
  ArrowRight,
  Home,
  Users,
  UserCheck,
  Smartphone,
  Lock,
  ShieldCheck,
  AlertCircle,
  Loader,
} from "lucide-react";
import { Logo } from "../App";
import { auth } from "../services/Firebase";
import {
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
} from "firebase/auth";

interface LoginProps {
  onLogin: (newState: AppState) => void;
}

const Login: React.FC<LoginProps> = ({ onLogin }) => {
  const [isRegistering, setIsRegistering] = useState(false);
  const [email, setEmail] = useState("");
  const [name, setName] = useState("");
  const [phone, setPhone] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [role, setRole] = useState<UserRole>(UserRole.TENANT);
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setIsLoading(true);
    try {
      const userCredential = await signInWithEmailAndPassword(
        auth,
        email,
        password
      );
      // After successful auth, fetch the entire app state from Firestore.
      const firestoreState = await fetchStoreFromFirestore();

      if (firestoreState) {
        const user = firestoreState.users.find(
          (u) => u.id === userCredential.user.uid
        );

        if (user) {
          // CRITICAL STEP: The entire fetched state must be saved locally
          // to sync the new device.
          firestoreState.currentUser = user; // Set current user in the state
          await saveStore(firestoreState); // This saves to localStorage AND Firestore

          // Now, trigger the onLogin callback with the complete, fresh state.
          onLogin(firestoreState);
        } else {
          setError(
            "Login successful, but user data not found in the database. Contact support."
          );
        }
      } else {
        setError("Could not fetch application data. Please try again.");
      }
    } catch (error) {
      setError("Invalid email or password. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");

    if (password !== confirmPassword) {
      setError("Passwords do not match.");
      return;
    }
    if (password.length < 6) {
      setError("Password must be at least 6 characters long.");
      return;
    }

    setIsLoading(true);

    try {
      const userCredential = await createUserWithEmailAndPassword(
        auth,
        email,
        password,
      );
      const { uid } = userCredential.user;

      const referralAgentId = localStorage.getItem("referral_agent_id");
      // Create a user object *without* the displayId. It will be generated by saveUser.
      const newUser: Omit<User, 'displayId'> = {
        id: uid,
        name,
        email,
        phone,
        role,
        agentId: role === UserRole.TENANT ? referralAgentId : undefined,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      const success = await saveUser(newUser);

      if (success) {
        if (referralAgentId) {
          localStorage.removeItem("referral_agent_id");
        }
        // After saving, get the full updated state which now includes the new user with their displayId
        const updatedStore = getStore();
        const userInStore = updatedStore.users.find(u => u.id === uid);
        updatedStore.currentUser = userInStore || null;
        await saveStore(updatedStore); // Ensure currentUser is persisted

        onLogin(updatedStore);
      } else {
        await userCredential.user.delete();
        setError(
          "Could not save user data. Your registration has been cancelled. Please try again.",
        );
      }
    } catch (error: any) {
      if (error.code === "auth/email-already-in-use") {
        setError(
          "An account with this email already exists. Please try logging in.",
        );
      } else {
        setError("Failed to create account. Email might be taken or invalid.");
      }
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-offwhite dark:bg-zinc-900 text-zinc-900 dark:text-white flex items-center justify-center p-4">
      <div className="w-full max-w-lg mx-auto">
        <div className="glass-card p-8 md:p-12 rounded-3xl shadow-2xl w-full">
          <div className="text-center mb-8">
            <div className="inline-block p-4 bg-blue-600/10 rounded-2xl mb-4">
              <Logo size={32} className="text-blue-600" />
            </div>
            <h1 className="text-3xl font-bold tracking-tighter">
              {isRegistering ? "Create Your Account" : "Welcome Back"}
            </h1>
            <p className="text-zinc-500 dark:text-zinc-400 mt-2">
              {isRegistering
                ? "Join us to streamline your property management."
                : "Sign in to manage your properties."}
            </p>
          </div>

          {error && (
            <div className="bg-red-500/10 text-red-500 border border-red-500/20 text-sm font-bold p-3 rounded-xl mb-6 flex items-center gap-3">
              <AlertCircle size={20} />
              <span>{error}</span>
            </div>
          )}

          <form onSubmit={isRegistering ? handleRegister : handleLogin}>
            <div className="space-y-5">
              {isRegistering && (
                <div className="flex gap-4">
                  <div className="relative w-1/2">
                    <input
                      type="text"
                      placeholder="Full Name"
                      value={name}
                      onChange={(e) => setName(e.target.value)}
                      required
                      className="w-full bg-white/50 dark:bg-black/20 p-4 pl-12 rounded-xl focus:outline-none focus:ring-2 ring-blue-500 transition-all"
                    />
                    <UserCheck className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400" />
                  </div>
                  <div className="relative w-1/2">
                    <input
                      type="tel"
                      placeholder="Phone Number"
                      value={phone}
                      onChange={(e) => setPhone(e.target.value)}
                      required
                      className="w-full bg-white/50 dark:bg-black/20 p-4 pl-12 rounded-xl focus:outline-none focus:ring-2 ring-blue-500 transition-all"
                    />
                    <Smartphone className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400" />
                  </div>
                </div>
              )}

              <div className="relative">
                <input
                  type="email"
                  placeholder="Email Address"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  required
                  className="w-full bg-white/50 dark:bg-black/20 p-4 pl-12 rounded-xl focus:outline-none focus:ring-2 ring-blue-500 transition-all"
                />
                <Mail className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400" />
              </div>

              <div className="relative">
                <input
                  type="password"
                  placeholder="Password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                  className="w-full bg-white/50 dark:bg-black/20 p-4 pl-12 rounded-xl focus:outline-none focus:ring-2 ring-blue-500 transition-all"
                />
                <Lock className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400" />
              </div>

              {isRegistering && (
                <div className="relative">
                  <input
                    type="password"
                    placeholder="Confirm Password"
                    value={confirmPassword}
                    onChange={(e) => setConfirmPassword(e.target.value)}
                    required
                    className="w-full bg-white/50 dark:bg-black/20 p-4 pl-12 rounded-xl focus:outline-none focus:ring-2 ring-blue-500 transition-all"
                  />
                  <ShieldCheck className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400" />
                </div>
              )}

              {isRegistering && (
                <div className="pt-2">
                  <p className="text-sm font-bold mb-3 text-zinc-500 dark:text-zinc-400">
                    I am registering as a...
                  </p>
                  <div className="grid grid-cols-2 gap-3">
                    <button
                      type="button"
                      onClick={() => setRole(UserRole.TENANT)}
                      className={`flex items-center justify-center text-center p-4 rounded-xl border-2 transition-all ${role === UserRole.TENANT ? "border-blue-500 bg-blue-500/10" : "border-zinc-200 dark:border-zinc-700 hover:border-zinc-400"}`}
                    >
                      <Home className="mr-3" />
                      <span className="font-semibold">Tenant</span>
                    </button>
                    <button
                      type="button"
                      onClick={() => setRole(UserRole.AGENT)}
                      className={`flex items-center justify-center text-center p-4 rounded-xl border-2 transition-all ${role === UserRole.AGENT ? "border-purple-500 bg-purple-500/10" : "border-zinc-200 dark:border-zinc-700 hover:border-zinc-400"}`}
                    >
                      <Users className="mr-3" />
                      <span className="font-semibold">Agent</span>
                    </button>
                  </div>
                </div>
              )}
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className="w-full bg-blue-600 text-white p-4 rounded-xl font-bold text-lg mt-8 hover:bg-blue-700 transition-all flex items-center justify-center gap-3 group disabled:bg-blue-400 disabled:cursor-not-allowed"
            >
              {isLoading ? (
                <>
                  <Loader className="animate-spin" />
                  <span>Processing...</span>
                </>
              ) : (
                <>
                  <span>{isRegistering ? "Create Account" : "Sign In"}</span>
                  <ArrowRight className="transition-transform group-hover:translate-x-1" />
                </>
              )}
            </button>
          </form>

          <div className="text-center mt-8">
            <button
              onClick={() => {
                setIsRegistering(!isRegistering);
                setError("");
              }}
              className="font-semibold text-blue-600 dark:text-blue-400 hover:underline"
            >
              {isRegistering
                ? "Already have an account? Sign In"
                : "Don't have an account? Register"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;
